// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'highlight-ask-pane-header'
  | 'highlight-ask-pane-sidenav'
  | 'highlightask-name';
