// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "apiKey": string;
      "baseUrl": string;
      "model": string;
      "thinkingParams": string;
      "temperature": string;
      "showReasoning": boolean;
      "promptRole": string;
      "promptScenario": string;
      "promptTaskExplain": string;
      "promptTaskTranslate": string;
      "promptTaskRole": string;
      "sendNearby": boolean;
      "sendFullText": boolean;
      "fullTextMaxChars": number;
      "saveToNote": boolean;
      "saveToJson": boolean;
      "logRequests": boolean;
    };
  }
}
